/**
 * Shared building blocks for generated dApp projects.
 *
 * Generated source is written as plain strings. Rule for every template in
 * this folder: generated code must not contain backticks or "${", so it can
 * live safely inside the generator's own template literals.
 */

export interface TemplateContract {
  name: string
  address: string
  abi: any[]
  chainId: number
}

export interface TemplateContext {
  projectName: string
  contract: TemplateContract
  /** Import path prefix for app-local modules ("@/" for both Next and Vite) */
  alias: string
  /** Emit "use client" directives (Next.js only) */
  useClient: boolean
}

/** Pinned, mutually compatible dependency versions (checked against npm peer deps) */
export const VERSIONS = {
  next: "^16.3.6",
  react: "^19.3.0",
  reactDom: "^19.3.0",
  // RainbowKit 2.x requires wagmi ^2 — do not bump wagmi to 3 until RainbowKit supports it
  wagmi: "^2.19.5",
  viem: "^2.56.9",
  rainbowkit: "^2.2.11",
  reactQuery: "^5.104.0",
  tailwind: "^4.3.3",
  tailwindPostcss: "^4.3.3",
  tailwindVite: "^4.3.3",
  vite: "^8.3.1",
  viteReact: "^6.1.1",
  typescript: "^5.9.3",
  typesReact: "^19.3.0",
  typesReactDom: "^19.3.0",
  typesNode: "^22.19.0",
}

export const MEZO_LINKS = {
  docs: "https://mezo.org/docs",
  developers: "https://mezo.org/docs/developers",
  faucet: "https://faucet.test.mezo.org",
  passport: "https://www.npmjs.com/package/@mezo-org/passport",
  walletConnect: "https://cloud.reown.com",
}

export function networkInfo(chainId: number) {
  const isMainnet = chainId === 31612
  return {
    chainImport: isMainnet ? "mezoMainnet" : "mezoTestnet",
    label: isMainnet ? "Mezo Mainnet" : "Mezo Testnet",
    explorer: isMainnet ? "https://explorer.mezo.org" : "https://explorer.test.mezo.org",
    isMainnet,
  }
}

/** npm-safe package name */
export function sanitizeProjectName(input: string): string {
  const cleaned = input
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, "-")
    .replace(/^[._-]+/, "")
    .replace(/-+/g, "-")
    .replace(/-$/, "")
    .slice(0, 214)
  return cleaned || "mezo-dapp"
}

/** Safe for use inside a double-quoted JS/JSON string and in HTML text */
export function escapeText(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/</g, "&lt;").replace(/>/g, "&gt;")
}

const directive = (ctx: TemplateContext) => (ctx.useClient ? '"use client";\n\n' : "")

/* ------------------------------------------------------------------ */
/* lib/contract.ts                                                      */
/* ------------------------------------------------------------------ */

/* ------------------------------------------------------------------ */
/* lib/chains.ts — Mezo chains with documented RPCs + fallback          */
/* ------------------------------------------------------------------ */

export function chainsFile(): string {
  return `import { fallback, http, type Chain } from "viem";
import { mezo, mezoTestnet as viemMezoTestnet } from "viem/chains";

// Mezo's documented public RPC providers:
// https://mezo.org/docs/developers/getting-started/configure-environment/
const MAINNET_RPCS = [
  "https://mezo-mainnet.boar.network",
  "https://mainnet.mezo.public.validationcloud.io",
  "https://mezo.drpc.org",
  "https://rpc_evm-mezo.imperator.co",
];
const TESTNET_RPCS = ["https://rpc.test.mezo.org"];

export const mezoMainnet = { ...mezo, rpcUrls: { default: { http: MAINNET_RPCS } } } as const satisfies Chain;
export const mezoTestnet = { ...viemMezoTestnet, rpcUrls: { default: { http: TESTNET_RPCS } } } as const satisfies Chain;

/** Tries each RPC in order, so one provider being down doesn't break the app */
export function rpcTransport(chain: Chain) {
  return fallback(chain.rpcUrls.default.http.map((url) => http(url)));
}
`
}

export function contractFile(ctx: TemplateContext): string {
  const { contract } = ctx
  const net = networkInfo(contract.chainId)
  return `import { ${net.chainImport} } from "${ctx.alias}lib/chains";

/**
 * ${escapeText(contract.name)} — deployed on ${net.label} (chain ID ${contract.chainId}).
 * Generated by Mezo IDE. The ABI is declared "as const", so wagmi/viem infer
 * function names, argument and return types when you use it directly.
 */
export const CONTRACT_NAME = "${escapeText(contract.name)}";

export const CONTRACT_ADDRESS = "${contract.address}" as const;

export const CONTRACT_CHAIN = ${net.chainImport};

export const CONTRACT_ABI = ${JSON.stringify(contract.abi, null, 2)} as const;
`
}

/* ------------------------------------------------------------------ */
/* lib/abi.ts — ABI parsing / formatting helpers                       */
/* ------------------------------------------------------------------ */

export function abiHelpersFile(): string {
  return `import { isAddress, isHex, type Abi, type AbiFunction, type AbiParameter } from "viem";

export function getFunctions(abi: Abi) {
  const functions = abi.filter((item): item is AbiFunction => item.type === "function");
  return {
    reads: functions.filter((f) => f.stateMutability === "view" || f.stateMutability === "pure"),
    writes: functions.filter((f) => f.stateMutability === "nonpayable" || f.stateMutability === "payable"),
  };
}

/** Unique key for a function (handles overloads) */
export function signature(fn: AbiFunction): string {
  return fn.name + "(" + fn.inputs.map((input) => input.type).join(",") + ")";
}

/** Whether an input is entered as JSON (arrays and tuples) */
export function isComplex(param: AbiParameter): boolean {
  return param.type.endsWith("]") || param.type.startsWith("tuple");
}

export function placeholderFor(param: AbiParameter): string {
  if (param.type.endsWith("]")) return "JSON array, e.g. [1, 2]";
  if (param.type.startsWith("tuple")) return "JSON object or array";
  if (param.type === "address") return "0x...";
  if (param.type === "bool") return "true or false";
  if (param.type.startsWith("bytes")) return "0x... (hex)";
  if (param.type.startsWith("uint") || param.type.startsWith("int")) return "Integer (wei for token amounts)";
  return param.type;
}

function label(param: AbiParameter): string {
  return (param.name || "argument") + " (" + param.type + ")";
}

function coerce(param: AbiParameter, value: unknown): unknown {
  const { type } = param;

  if (type.endsWith("]")) {
    if (!Array.isArray(value)) throw new Error(label(param) + " must be a JSON array");
    const inner = { ...param, type: type.slice(0, type.lastIndexOf("[")) } as AbiParameter;
    return value.map((item) => coerce(inner, item));
  }

  if (type.startsWith("tuple")) {
    const components = (param as { components?: readonly AbiParameter[] }).components ?? [];
    if (Array.isArray(value)) return components.map((c, i) => coerce(c, value[i]));
    if (value && typeof value === "object") {
      const record = value as Record<string, unknown>;
      return Object.fromEntries(components.map((c, i) => [c.name || String(i), coerce(c, record[c.name || String(i)])]));
    }
    throw new Error(label(param) + " must be a JSON object or array");
  }

  const text = typeof value === "string" ? value.trim() : String(value ?? "").trim();

  if (type.startsWith("uint") || type.startsWith("int")) {
    if (!/^-?\\d+$/.test(text)) throw new Error(label(param) + " must be a whole number");
    const n = BigInt(text);
    if (type.startsWith("uint") && n < BigInt(0)) throw new Error(label(param) + " cannot be negative");
    return n;
  }

  if (type === "bool") {
    if (value === true || text === "true" || text === "1") return true;
    if (value === false || text === "false" || text === "0") return false;
    throw new Error(label(param) + " must be true or false");
  }

  if (type === "address") {
    if (!isAddress(text)) throw new Error(label(param) + " is not a valid address");
    return text;
  }

  if (type.startsWith("bytes")) {
    if (!isHex(text)) throw new Error(label(param) + " must be 0x-prefixed hex");
    return text;
  }

  return typeof value === "string" ? value : text;
}

/** Turn raw form strings into typed arguments for viem */
export function parseArgs(fn: AbiFunction, raw: Record<string, string>): unknown[] {
  return fn.inputs.map((param, index) => {
    const key = String(index);
    const value = raw[key] ?? "";
    if (isComplex(param)) {
      if (!value.trim()) throw new Error(label(param) + " is required");
      let parsed: unknown;
      try {
        parsed = JSON.parse(value);
      } catch {
        throw new Error(label(param) + " must be valid JSON");
      }
      return coerce(param, parsed);
    }
    if (!value.trim() && param.type !== "string") throw new Error(label(param) + " is required");
    return coerce(param, value);
  });
}

/** Pretty-print any return value (bigint-safe) */
export function formatResult(value: unknown): string {
  if (value === undefined) return "—";
  if (typeof value === "bigint") return value.toString();
  if (typeof value === "string") return value;
  return JSON.stringify(value, (_key, v) => (typeof v === "bigint" ? v.toString() : v), 2);
}

/** Human-readable error from viem / wagmi / wallets */
export function errorMessage(error: unknown): string {
  if (error && typeof error === "object") {
    const e = error as { shortMessage?: string; details?: string; message?: string };
    if (e.shortMessage) {
      const short = e.shortMessage.replace(/\\s*\\n+\\s*/g, " ");
      // Revert reasons are already in shortMessage; otherwise add the RPC details
      return e.details && !/reason:/i.test(short) ? short + " (" + e.details + ")" : short;
    }
    if (e.message) return e.message.split("\\n")[0];
  }
  return String(error);
}
`
}

/* ------------------------------------------------------------------ */
/* components/contract-panel.tsx — ABI-driven UI (stack agnostic)      */
/* Depends on "@/lib/actions" (useContractActions) per template.       */
/* ------------------------------------------------------------------ */

export function contractPanelFile(ctx: TemplateContext): string {
  const a = ctx.alias
  return `${directive(ctx)}import { useEffect, useMemo, useState, type ReactNode } from "react";
import { parseEther, type Abi, type AbiFunction, type Hash } from "viem";
import { CONTRACT_ABI, CONTRACT_ADDRESS, CONTRACT_CHAIN, CONTRACT_NAME } from "${a}lib/contract";
import { errorMessage, formatResult, getFunctions, isComplex, parseArgs, placeholderFor, signature } from "${a}lib/abi";
import { useContractActions } from "${a}lib/actions";

const abi = CONTRACT_ABI as unknown as Abi;
const explorer = CONTRACT_CHAIN.blockExplorers?.default.url;

function cn(...classes: Array<string | false | null | undefined>) {
  return classes.filter(Boolean).join(" ");
}

export function ContractPanel() {
  const { reads, writes } = useMemo(() => getFunctions(abi), []);
  const [tab, setTab] = useState<"read" | "write">(reads.length > 0 ? "read" : "write");
  const actions = useContractActions();

  return (
    <section className="border border-white/10 bg-surface">
      <header className="flex flex-wrap items-start justify-between gap-3 border-b border-white/10 p-5">
        <div className="min-w-0">
          <h2 className="text-lg font-medium">{CONTRACT_NAME}</h2>
          <a
            href={explorer ? explorer + "/address/" + CONTRACT_ADDRESS : undefined}
            target="_blank"
            rel="noreferrer"
            className="break-all font-mono text-xs text-white/50 hover:text-accent"
          >
            {CONTRACT_ADDRESS}
          </a>
        </div>
        <span className="rounded-sm bg-accent/10 px-2 py-1 text-xs text-accent">{CONTRACT_CHAIN.name}</span>
      </header>

      {actions.isConnected && actions.isWrongNetwork && (
        <div className="flex flex-wrap items-center justify-between gap-3 border-b border-amber-500/20 bg-amber-500/10 px-5 py-3 text-sm text-amber-400">
          <span>Your wallet is on another network. Switch to {CONTRACT_CHAIN.name} to send transactions.</span>
          <button onClick={() => actions.switchNetwork()} className="bg-amber-400 px-3 py-1.5 text-xs font-medium text-black hover:bg-amber-300">
            Switch network
          </button>
        </div>
      )}

      <nav className="flex gap-6 border-b border-white/10 px-5">
        {(["read", "write"] as const).map((key) => (
          <button
            key={key}
            onClick={() => setTab(key)}
            className={cn(
              "relative py-3 text-sm font-medium capitalize transition-colors",
              tab === key ? "text-accent" : "text-white/60 hover:text-white"
            )}
          >
            {key} ({key === "read" ? reads.length : writes.length})
            {tab === key && <span className="absolute bottom-0 left-0 h-0.5 w-full bg-accent" />}
          </button>
        ))}
      </nav>

      <div className="space-y-3 p-5">
        {(tab === "read" ? reads : writes).length === 0 && (
          <p className="py-8 text-center text-sm text-white/50">This contract has no {tab} functions.</p>
        )}
        {tab === "read" && reads.map((fn) => <ReadFunction key={signature(fn)} fn={fn} />)}
        {tab === "write" && writes.map((fn) => <WriteFunction key={signature(fn)} fn={fn} />)}
      </div>
    </section>
  );
}

function ArgInputs({
  fn,
  values,
  onChange,
}: {
  fn: AbiFunction;
  values: Record<string, string>;
  onChange: (key: string, value: string) => void;
}) {
  if (fn.inputs.length === 0) return null;
  return (
    <div className="space-y-2">
      {fn.inputs.map((param, index) => {
        const key = String(index);
        const common = {
          value: values[key] ?? "",
          placeholder: placeholderFor(param),
          className:
            "w-full border border-white/10 bg-black px-3 py-2 font-mono text-xs text-white placeholder:text-white/30 focus:border-accent/50 focus:outline-none",
        };
        return (
          <label key={key} className="block space-y-1">
            <span className="text-[11px] uppercase tracking-wider text-white/40">
              {param.name || "arg" + index} <span className="normal-case text-white/30">{param.type}</span>
            </span>
            {isComplex(param) ? (
              <textarea rows={3} {...common} onChange={(e) => onChange(key, e.target.value)} />
            ) : (
              <input {...common} onChange={(e) => onChange(key, e.target.value)} />
            )}
          </label>
        );
      })}
    </div>
  );
}

function FunctionShell({
  fn,
  badge,
  children,
  defaultOpen,
}: {
  fn: AbiFunction;
  badge: string;
  children: ReactNode;
  defaultOpen?: boolean;
}) {
  const [open, setOpen] = useState(!!defaultOpen);
  return (
    <div className="border border-white/10">
      <button onClick={() => setOpen(!open)} className="flex w-full items-center justify-between gap-3 px-4 py-3 text-left hover:bg-white/5">
        <span className="truncate font-mono text-sm">
          {fn.name}
          <span className="text-white/40">({fn.inputs.map((i) => i.type).join(", ")})</span>
        </span>
        <span className="shrink-0 rounded-sm bg-white/10 px-1.5 py-0.5 text-[10px] uppercase text-white/60">{badge}</span>
      </button>
      {open && <div className="space-y-3 border-t border-white/10 p-4">{children}</div>}
    </div>
  );
}

function ReadFunction({ fn }: { fn: AbiFunction }) {
  const { read } = useContractActions();
  const [values, setValues] = useState<Record<string, string>>({});
  const [result, setResult] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const run = async () => {
    setLoading(true);
    setError(null);
    try {
      const args = parseArgs(fn, values);
      setResult(formatResult(await read(fn.name, args)));
    } catch (e) {
      setResult(null);
      setError(errorMessage(e));
    } finally {
      setLoading(false);
    }
  };

  // Functions without arguments load immediately
  useEffect(() => {
    if (fn.inputs.length === 0) void run();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <FunctionShell fn={fn} badge={fn.stateMutability} defaultOpen={fn.inputs.length === 0}>
      <ArgInputs fn={fn} values={values} onChange={(k, v) => setValues((prev) => ({ ...prev, [k]: v }))} />
      <button
        onClick={run}
        disabled={loading}
        className="border border-white/10 bg-white/5 px-3 py-1.5 text-xs font-medium hover:bg-white/10 disabled:opacity-50"
      >
        {loading ? "Reading..." : fn.inputs.length === 0 ? "Refresh" : "Query"}
      </button>
      {result !== null && (
        <pre className="overflow-x-auto whitespace-pre-wrap break-all border border-white/10 bg-black p-3 font-mono text-xs text-accent">{result}</pre>
      )}
      {error && <p className="break-words text-xs text-red-400">{error}</p>}
    </FunctionShell>
  );
}

function WriteFunction({ fn }: { fn: AbiFunction }) {
  const { write, isConnected, connect } = useContractActions();
  const [values, setValues] = useState<Record<string, string>>({});
  const [btcValue, setBtcValue] = useState("");
  const [status, setStatus] = useState<"idle" | "pending" | "confirming" | "success" | "reverted">("idle");
  const [hash, setHash] = useState<Hash | null>(null);
  const [error, setError] = useState<string | null>(null);
  const isPayable = fn.stateMutability === "payable";

  const submit = async () => {
    if (!isConnected) {
      connect();
      return;
    }
    setError(null);
    setHash(null);
    try {
      const args = parseArgs(fn, values);
      const value = isPayable && btcValue.trim() ? parseEther(btcValue.trim()) : undefined;
      setStatus("pending");
      const receipt = await write(fn.name, args, value, (txHash) => {
        setHash(txHash);
        setStatus("confirming");
      });
      setStatus(receipt.status === "success" ? "success" : "reverted");
    } catch (e) {
      setStatus("idle");
      setError(errorMessage(e));
    }
  };

  const busy = status === "pending" || status === "confirming";

  return (
    <FunctionShell fn={fn} badge={isPayable ? "payable" : "write"}>
      <ArgInputs fn={fn} values={values} onChange={(k, v) => setValues((prev) => ({ ...prev, [k]: v }))} />
      {isPayable && (
        <label className="block space-y-1">
          <span className="text-[11px] uppercase tracking-wider text-white/40">
            Value <span className="normal-case text-white/30">BTC</span>
          </span>
          <input
            value={btcValue}
            onChange={(e) => setBtcValue(e.target.value)}
            placeholder="0.0"
            inputMode="decimal"
            className="w-full border border-white/10 bg-black px-3 py-2 font-mono text-xs text-white placeholder:text-white/30 focus:border-accent/50 focus:outline-none"
          />
        </label>
      )}
      <button
        onClick={submit}
        disabled={busy}
        className="bg-accent px-3 py-1.5 text-xs font-medium text-black hover:opacity-90 disabled:opacity-50"
      >
        {!isConnected
          ? "Connect wallet"
          : status === "pending"
            ? "Confirm in wallet..."
            : status === "confirming"
              ? "Confirming..."
              : "Send transaction"}
      </button>
      {hash && (
        <p className="text-xs text-white/60">
          {status === "success" && <span className="text-green-400">Confirmed. </span>}
          {status === "reverted" && <span className="text-red-400">Reverted. </span>}
          <a
            href={explorer ? explorer + "/tx/" + hash : undefined}
            target="_blank"
            rel="noreferrer"
            className="break-all font-mono text-accent hover:underline"
          >
            {hash}
          </a>
        </p>
      )}
      {error && <p className="break-words text-xs text-red-400">{error}</p>}
    </FunctionShell>
  );
}
`
}

/* ------------------------------------------------------------------ */
/* Page body used by every template                                    */
/* ------------------------------------------------------------------ */

export function pageBody(ctx: TemplateContext, connectButton: string): string {
  const net = networkInfo(ctx.contract.chainId)
  return `    <main className="min-h-screen px-6 py-10">
      <div className="mx-auto max-w-3xl space-y-8">
        <header className="flex flex-wrap items-center justify-between gap-4">
          <div>
            <h1 className="text-2xl font-medium">${escapeText(ctx.projectName)}</h1>
            <p className="mt-1 text-sm text-white/60">
              Interact with ${escapeText(ctx.contract.name)} on ${net.label}
            </p>
          </div>
          ${connectButton}
        </header>

        <ContractPanel />

        <footer className="text-xs text-white/40">
          Built on <a className="text-accent hover:underline" href="${MEZO_LINKS.docs}" target="_blank" rel="noreferrer">Mezo</a>
          ${net.isMainnet ? "" : `· Need testnet BTC? <a className="text-accent hover:underline" href="${MEZO_LINKS.faucet}" target="_blank" rel="noreferrer">Mezo faucet</a>`}
        </footer>
      </div>
    </main>`
}

export function stylesFile(): string {
  return `@import "tailwindcss";

/* Change --color-accent to re-brand the whole app */
@theme {
  --color-accent: #b3ec11;
  --color-surface: #0a0a0a;
}

html,
body {
  background: #000;
  color: #fafafa;
}

body {
  font-family: ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif;
}
`
}

export function gitignoreFile(): string {
  return `# dependencies
node_modules

# builds
.next/
out/
dist/
build/

# env
.env
.env*.local

# misc
.DS_Store
*.pem
*.tsbuildinfo
next-env.d.ts
npm-debug.log*
`
}

export function readmeFile(
  ctx: TemplateContext,
  opts: { stack: string; envVar?: string; devUrl: string; structure: string; walletSection: string }
): string {
  const { contract } = ctx
  const net = networkInfo(contract.chainId)
  return `# ${ctx.projectName}

A dApp for **${contract.name}** on ${net.label}, generated by Mezo IDE.

- Contract: [\`${contract.address}\`](${net.explorer}/address/${contract.address})
- Network: ${net.label} (chain ID ${contract.chainId})
- Stack: ${opts.stack}

## Getting started

Requires Node.js 20.9 or newer.

\`\`\`bash
npm install
${opts.envVar ? "cp .env.example .env.local   # optional, see below\n" : ""}npm run dev
\`\`\`

Open ${opts.devUrl}.

${opts.walletSection}

## What you get

- **Read tab** — every \`view\`/\`pure\` function. Functions without arguments load automatically.
- **Write tab** — every state-changing function, with BTC value input for \`payable\` functions.
  Transactions are simulated first, so revert reasons show before your wallet opens.
- Wrong-network detection with a one-click switch to ${net.label}.
- Arrays and structs are entered as JSON, for example \`[1, 2, 3]\` or \`{"to": "0x...", "amount": "100"}\`.
  Integers are raw base units: 1 token with 18 decimals is \`1000000000000000000\`.

## Project structure

${opts.structure}

## Using the contract in your own components

\`CONTRACT_ABI\` is declared \`as const\`, so calls are fully typed:

\`\`\`ts
import { CONTRACT_ABI, CONTRACT_ADDRESS, CONTRACT_CHAIN } from "@/lib/contract";
\`\`\`

Pass them to wagmi's \`useReadContract\` / \`useWriteContract\`, or viem's \`readContract\` / \`writeContract\`.

## Scripts

| Command | Description |
| --- | --- |
| \`npm run dev\` | Start the dev server |
| \`npm run build\` | Production build |
| \`npm run typecheck\` | Type-check the project |

## Mezo resources

- [Mezo documentation](${MEZO_LINKS.docs})
- [Developer docs](${MEZO_LINKS.developers})
${net.isMainnet ? "" : `- [Testnet faucet](${MEZO_LINKS.faucet}) — get testnet BTC for gas\n`}- [Explorer](${net.explorer})
- [Mezo Passport](${MEZO_LINKS.passport}) — Mezo's wallet kit that adds Bitcoin wallets (Unisat, OKX, Xverse) on top of RainbowKit.
  At the time of generation it requires React 18, so it isn't bundled here.
`
}
