export const BillingV2Abi = {
  contractName: 'MezoHostBillingV2',
  abi: [
    {
      inputs: [
        { internalType: 'address', name: '_token', type: 'address' },
        { internalType: 'address', name: '_treasury', type: 'address' },
      ],
      stateMutability: 'nonpayable',
      type: 'constructor',
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, internalType: 'address', name: 'user', type: 'address' },
        { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
      ],
      name: 'AccountToppedUp',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, internalType: 'address', name: 'whale', type: 'address' },
        { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
        { indexed: false, internalType: 'uint256', name: 'unlockTime', type: 'uint256' },
        { indexed: false, internalType: 'uint256', name: 'lockTime', type: 'uint256' },
      ],
      name: 'CollateralLocked',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
        { indexed: false, internalType: 'uint256', name: 'timestamp', type: 'uint256' },
      ],
      name: 'CollateralMovedToTreasury',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
        { indexed: false, internalType: 'uint256', name: 'timestamp', type: 'uint256' },
      ],
      name: 'CollateralReturnedFromTreasury',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, internalType: 'address', name: 'whale', type: 'address' },
        { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
        { indexed: false, internalType: 'bool', name: 'wasSlashed', type: 'bool' },
      ],
      name: 'CollateralWithdrawn',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, internalType: 'address', name: 'whale', type: 'address' },
        { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
        { indexed: false, internalType: 'uint256', name: 'timestamp', type: 'uint256' },
      ],
      name: 'WithdrawalQueued',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, internalType: 'address', name: 'whale', type: 'address' },
        { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
        { indexed: false, internalType: 'uint256', name: 'timestamp', type: 'uint256' },
      ],
      name: 'WithdrawalProcessed',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, internalType: 'address', name: 'whale', type: 'address' },
        { indexed: false, internalType: 'uint256', name: 'yieldAmount', type: 'uint256' },
        { indexed: false, internalType: 'uint256', name: 'timestamp', type: 'uint256' },
      ],
      name: 'YieldCredited',
      type: 'event',
    },
    {
      inputs: [],
      name: 'PENALTY_PERCENT',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: '_whale', type: 'address' }],
      name: 'getLockStatus',
      outputs: [
        { internalType: 'bool', name: 'isActive', type: 'bool' },
        { internalType: 'uint256', name: 'amount', type: 'uint256' },
        { internalType: 'uint256', name: 'unlockTimestamp', type: 'uint256' },
        { internalType: 'uint256', name: 'lockTimestamp', type: 'uint256' },
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: '_whale', type: 'address' }],
      name: 'getYieldStats',
      outputs: [
        { internalType: 'uint256', name: 'totalYield', type: 'uint256' },
        { internalType: 'uint256', name: 'lastCreditTime', type: 'uint256' },
        { internalType: 'uint256', name: 'lockedAmount', type: 'uint256' },
        { internalType: 'uint256', name: 'lockDurationRemaining', type: 'uint256' },
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: '_whale', type: 'address' }],
      name: 'getWithdrawalRequest',
      outputs: [
        { internalType: 'uint256', name: 'amount', type: 'uint256' },
        { internalType: 'uint256', name: 'requestTimestamp', type: 'uint256' },
        { internalType: 'bool', name: 'isPending', type: 'bool' },
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'getContractStatus',
      outputs: [
        { internalType: 'uint256', name: '_totalLocked', type: 'uint256' },
        { internalType: 'uint256', name: '_totalInTreasury', type: 'uint256' },
        { internalType: 'uint256', name: '_contractBalance', type: 'uint256' },
        { internalType: 'uint256', name: '_reserveRatio', type: 'uint256' },
        { internalType: 'uint256', name: '_availableToMove', type: 'uint256' },
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: '', type: 'address' }],
      name: 'lockedVaults',
      outputs: [
        { internalType: 'uint256', name: 'amount', type: 'uint256' },
        { internalType: 'uint256', name: 'unlockTimestamp', type: 'uint256' },
        { internalType: 'uint256', name: 'lockTimestamp', type: 'uint256' },
        { internalType: 'bool', name: 'isActive', type: 'bool' },
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: '', type: 'address' }],
      name: 'totalYieldCredited',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'totalLockedCollateral',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'totalInTreasury',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'reserveRatioBps',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'uint256', name: 'lockedAmount', type: 'uint256' },
        { internalType: 'uint256', name: 'annualYieldBps', type: 'uint256' },
      ],
      name: 'estimateDailyYield',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'pure',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'whale', type: 'address' },
        { internalType: 'uint256', name: 'yieldAmount', type: 'uint256' },
      ],
      name: 'creditYield',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address[]', name: 'whales', type: 'address[]' },
        { internalType: 'uint256[]', name: 'yieldAmounts', type: 'uint256[]' },
      ],
      name: 'batchCreditYield',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
  ],
};
