import type { Metadata } from "next"
import "./globals.css"
import localFont from "next/font/local"
import { AntProvider } from "@/components/utilities/ant-provider"
import { ToastContainer } from "react-toastify"
import "react-toastify/dist/ReactToastify.css"
import { TanstackProvider } from "@/components/utilities/tanstack-provider"

const suiFont = localFont({
  src: [
    {
      path: "./fonts/SuisseIntl-Light.woff2",
      weight: "300",
    },
    {
      path: "./fonts/SuisseIntl-Regular.woff2",
      weight: "400",
    },
    {
      path: "./fonts/SuisseIntl-Medium.woff2",
      weight: "500",
    },
  ],
  variable: "--font-suisse-intl",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={`${suiFont.variable} ${suiFont.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <TanstackProvider>
          <AntProvider>{children}</AntProvider>
          <ToastContainer />
        </TanstackProvider>
      </body>
    </html>
  )
}
