import type { Metadata } from "next"
import "./globals.css"
import localFont from "next/font/local"

const suiFont = localFont({
  src: [
    {
      path: "./fonts/SuisseIntl-Light.woff2",
      weight: "300",
    },
    {
      path: "./fonts/SuisseIntl-Regular.woff2",
      weight: "400",
    },
    {
      path: "./fonts/SuisseIntl-Medium.woff2",
      weight: "500",
    },
  ],
  variable: "--font-suisse-intl",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={`${suiFont.variable} ${suiFont.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  )
}
