"use client"

import { useRef } from "react"
import gsap from "gsap"
import { useGSAP } from "@gsap/react"
import { ScrollTrigger } from "gsap/ScrollTrigger"
import { Bitcoin, CreditCard } from "lucide-react"

gsap.registerPlugin(useGSAP, ScrollTrigger)

export default function GsapFeatures() {
  const container = useRef<HTMLDivElement>(null)
  
  useGSAP(() => {
    const cards = gsap.utils.toArray<HTMLElement>(".feature-card")
    
    cards.forEach((card, i) => {
      gsap.from(card, {
        scrollTrigger: {
          trigger: card,
          start: "top 85%",
          toggleActions: "play none none reverse"
        },
        y: 100,
        opacity: 0,
        rotateX: -15,
        duration: 1,
        ease: "power3.out",
        delay: i * 0.1
      })
    })

    // Subtitle reveal
    gsap.from(".feature-heading", {
      scrollTrigger: {
        trigger: ".feature-heading",
        start: "top 80%"
      },
      opacity: 0,
      y: 30,
      stagger: 0.1,
      duration: 0.8
    })

  }, { scope: container })

  return (
    <section ref={container} className="relative bg-black py-32 px-6 overflow-hidden perspective-1000">
      
      {/* Background brutalist accents */}
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[80vw] h-[1px] bg-white/5 pointer-events-none" />
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 h-[80vh] w-[1px] bg-white/5 pointer-events-none" />
      
      <div className="max-w-6xl mx-auto z-10 relative">
        <div className="text-center mb-24">
          <div className="font-mono text-sm text-white/40 mb-4 tracking-widest uppercase feature-heading">
            Blockchain Economics
          </div>
          <h2 className="text-4xl md:text-7xl font-semibold tracking-tighter text-white feature-heading">
            Yield for <span className="text-white/50">Compute.</span>
          </h2>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 md:gap-12">
          
          {/* Pro Developer Card */}
          <div 
            className="feature-card bg-[#0a0a0c] border border-white/10 p-10 md:p-14 relative flex flex-col justify-between min-h-[400px] group hover:border-white/20 transition-colors"
            style={{ clipPath: "polygon(0 0, calc(100% - 24px) 0, 100% 24px, 100% 100%, 0 100%)" }}
          >
            <div className="absolute top-0 right-0 p-6">
              <Bitcoin size={48} className="text-white/10 group-hover:text-primary transition-colors" />
            </div>
            
            <div>
              <div className="font-mono text-xs uppercase tracking-widest text-primary mb-4 bg-primary/10 inline-block px-3 py-1 rounded-sm border border-primary/20">
                Tier 01: Pro Developer
              </div>
              <h3 className="text-3xl font-semibold text-white mb-6">Zero Sunk Cost.</h3>
              <p className="text-white/60 font-light leading-relaxed">
                Lock your stablecoins or native Mezo tokens into a Smart Contract Vault. The yield generated by your locked tokens pays for your server compute.
              </p>
            </div>

            <div className="mt-12 pt-6 border-t border-white/10">
              <p className="font-mono text-sm text-white/80">When you're done, unlock your initial deposit. You ran your servers for free.</p>
            </div>
          </div>

          {/* Regular Developer Card */}
          <div 
            className="feature-card bg-[#0a0a0c] border border-white/10 p-10 md:p-14 relative flex flex-col justify-between min-h-[400px] group hover:border-white/20 transition-colors"
            style={{ clipPath: "polygon(24px 0, 100% 0, 100% 100%, 0 100%, 0 24px)" }}
          >
            <div className="absolute top-0 right-0 p-6">
              <CreditCard size={48} className="text-white/10 group-hover:text-white/50 transition-colors" />
            </div>
            
            <div>
              <div className="font-mono text-xs uppercase tracking-widest text-white/40 mb-4 border border-white/10 inline-block px-3 py-1 rounded-sm">
                Tier 02: Regular Developer
              </div>
              <h3 className="text-3xl font-semibold text-white mb-6">Prepaid Credits.</h3>
              <p className="text-white/60 font-light leading-relaxed">
                Don't want to lock capital? Deposit tokens directly to mint MHCredits. Credits act as prepaid gas for running your containers.
              </p>
            </div>

            <div className="mt-12 pt-6 border-t border-white/10">
              <p className="font-mono text-sm text-white/80">Decentralized, programmatic billing. Container sleeps when credits run out.</p>
            </div>
          </div>

        </div>
      </div>
    </section>
  )
}
